apiVersion: v1
kind: Config
clusters:
- name: k3s-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpNM01qUTBOakF3SGhjTk1qVXhNVEl4TVRFeU56UXdXaGNOTXpVeE1URTVNVEV5TnpRdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpNM01qUTBOakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVktLQmZaUU10cjBmd3Q5b0F4VCtDbjhrL2wyRXkrcE9jbk1aNFFXTHUKWkJ2NlBZN3ozczBxRTBweXBxYjAxL2ZLS3ZMd3R1Ylp5dlJtbHJVa1FxWFVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU1GWlIxYkxRV1lURFE2ZnZyWnBWCkd2aGNNbXd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVArR2pQaEZ1eDljdGxmek55Sy9EK3dhU0dkWXBVVlEKdmdBNjhNK2cwZWh4QWlCVTB3ZnJzQWFOMk1uTEc5OENGcW1ZU242NWhaWFFsQlBUSStwTUd2NG1xZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://cluster.172.22.21.253.sslip.io:8080
contexts:
- name: dad-group-10-context
  context:
    cluster: k3s-cluster
    namespace: dad-group-10
    user: dad-group-10-sa
current-context: dad-group-10-context
users:
- name: dad-group-10-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkhHeVRNamQ5NFZleVdsOVRfNVRjcHRQdU1JeUJ0MXpKWk9SSDk2SWNlN2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkYWQtZ3JvdXAtMTAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGFkLWdyb3VwLTEwLXNhLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRhZC1ncm91cC0xMC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjljNjc0NTg5LTM4NzktNDhkMS04ZDFiLTNlODBmM2IzZTIwYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkYWQtZ3JvdXAtMTA6ZGFkLWdyb3VwLTEwLXNhIn0.L3R05HZiKS3rhh6oVOjKwH9BEfnqbsHHVXrMLUd5LLb7MmHXCKMA7irJEgQza4TSWIz0eYW0QvFdhzMB-li_aaj76CUB143bYpI5h5HpWM8YHvHvIFmMU9-hgUjL3VOA_DXVgJX9v_jnPbDdJVuH0FhGOcj5yyxbgUtq4RH6chEp3YnjZFeO_RuNbtyzFxqcRvQVLzBSFp6AzuMMsMXODEBoXUn5uBQHu5rapHXhMWSj7UkIQemTGQAXLKQfWEuFQUVcclPXkdmZ3HwhdqMplY9xUS8R32vD71lDDix__prLgjhHFPOarmrh7GpAl5eNsjadKtPCdIkqE8so8_tHDg